# Generated by Django 2.1.3 on 2018-12-10 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('read_statistics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='readdetail',
            options={'verbose_name': '阅读详情', 'verbose_name_plural': '阅读详情'},
        ),
        migrations.AlterModelOptions(
            name='readnum',
            options={'verbose_name': '阅读量', 'verbose_name_plural': '阅读量'},
        ),
    ]
