# Generated by Django 2.1.3 on 2018-12-10 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('read_statistics', '0002_auto_20181210_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readdetail',
            name='readnum_ptr',
        ),
        migrations.AlterModelOptions(
            name='readnum',
            options={},
        ),
        migrations.DeleteModel(
            name='ReadDetail',
        ),
    ]
